insert into adresses (street, city, postal_code, province, country) values ('465 Mont-Royal Ave E', 'Montreal', 'H2J 1W3', 'QC', 'Canada');
insert into adresses (street, city, postal_code, province, country) values ('900 Rue Riverside', 'Saint-Lambert', 'J4P 3P2', 'QC', 'Canada');

insert into libraries (name, phone, address_id ) values ('Bibliothèque de Montreal','+5148722270', 1);
insert into libraries (name, phone, address_id) values ('Bibliothèque de Saint-Lambert', '+14506727360', 2);

INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Lion, the Witch, and the Wardrobe', 'C.S. Lewis', 'true', '978-0-06-071082-6', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Hitchhikers Guide to the Galaxy', 'Douglas Adams', 'false', '978-0-330-25864-8', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Bell Jar', 'Sylvia Plath', 'true', '978-0-553-21223-2', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Silmarillion', 'J.R.R. Tolkien', 'false', '978-0-618-15397-5', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Color Purple', 'Alice Walker', 'true', '978-0-553-21375-0', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 'true', '978-0-7432-9335-3',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('To Kill a Mockingbird', 'Harper Lee', 'false', '978-0-449-00295-8',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('Pride and Prejudice', 'Jane Austen', 'true', '978-0-307-38789-8',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 'false', '978-0-307-27741-8',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Alchemist', 'Paulo Coelho', 'true', '978-0-06-112241-7',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('Wuthering Heights', 'Emily Brontë', 'false', '978-0-486-28202-8',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Picture of Dorian Gray', 'Oscar Wilde', 'true', '978-0-486-27806-6',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('One Hundred Years of Solitude', 'Gabriel García Márquez', 'false', '978-0-307-38883-1',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Grapes of Wrath', 'John Steinbeck', 'true', '978-0-670-32453-9',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('Moby-Dick', 'Herman Melville', 'false', '978-0-553-21364-4',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Adventures of Huckleberry Finn', 'Mark Twain', 'true', '978-0-513-00313-9',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Old Man and the Sea', 'Ernest Hemingway', 'false', '978-0-684-80001-0',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Great Expectations', 'Charles Dickens', 'true', '978-0-553-21271-3',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Brothers Karamazov', 'Fyodor Dostoevsky', 'false', '978-0-553-21242-3',1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Tale of Two Cities', 'Charles Dickens', 'true', '978-0-553-21218-8',2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('Brave New World', 'Aldous Huxley', TRUE, '978-0-553-21341-6', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Giver', 'Lois Lowry', FALSE, '978-0-385-74399-3', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Handmaids Tale', 'Margaret Atwood', TRUE, '978-0-385-49060-5', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Time Travelers Wife', 'Audrey Niffenegger', FALSE, '978-0-06-097742-4', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('1984', 'George Orwell', TRUE, '978-0-451-52493-6', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Maze Runner', 'James Dashner', FALSE, '978-0-385-38591-1', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Hunger Games', 'Suzanne Collins', TRUE, '978-0-307-51772-4', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Fault in Our Stars', 'John Green', FALSE, '978-0-575-08491-5', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Chronicles of Narnia', 'C.S. Lewis', TRUE, '978-0-06-256590-5', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('Looking for Alaska', 'John Green', FALSE, '978-0-525-47832-1', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Help', 'Kathryn Stockett', TRUE, '978-0-425-23320-3', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Shining', 'Stephen King', FALSE, '978-0-307-90716-5', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Shawshank Redemption', 'Stephen King', TRUE, '978-0-340-85565-1', 1);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Green Mile', 'Stephen King', FALSE, '978-0-452-27999-6', 2);
INSERT INTO books (title, author, available, ISBN, library_id) VALUES ('The Da Vinci Code', 'Dan Brown', TRUE, '978-0-307-47464-8', 1);

